# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-28 15:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.manager
import froala_editor.fields


class Migration(migrations.Migration):

    replaces = [('swing_admin', '0001_initial'), ('swing_admin', '0002_auto_20170828_1357'), ('swing_admin', '0003_auto_20170828_1401'), ('swing_admin', '0004_auto_20170828_1412'), ('swing_admin', '0005_auto_20170828_1440'), ('swing_admin', '0006_remove_news_image')]

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dates',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created')),
                ('modified', models.DateTimeField(auto_now=True)),
                ('deleted', models.DateTimeField(editable=False, null=True)),
                ('concealed', models.BooleanField(default=False, editable=False)),
                ('start', models.DateTimeField(verbose_name='Datum')),
                ('name', models.CharField(max_length=150, verbose_name='Veranstaltung')),
            ],
            options={
                'ordering': ['-created'],
                'get_latest_by': 'created',
                'abstract': False,
                'verbose_name': 'Date',
                'verbose_name_plural': 'Dates',
            },
            managers=[
                ('data', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created')),
                ('modified', models.DateTimeField(auto_now=True)),
                ('deleted', models.DateTimeField(editable=False, null=True)),
                ('concealed', models.BooleanField(default=False, editable=False)),
                ('title', models.CharField(max_length=100, verbose_name='Titel')),
                ('text', froala_editor.fields.FroalaField(verbose_name='Nachricht')),
            ],
            options={
                'ordering': ['-created'],
                'get_latest_by': 'created',
                'abstract': False,
                'verbose_name': 'News',
                'verbose_name_plural': 'News',
            },
            managers=[
                ('data', django.db.models.manager.Manager()),
            ],
        ),
    ]
