# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-28 15:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('swing_admin', '0001_squashed_0006_remove_news_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dates',
            options={'verbose_name': 'Date', 'verbose_name_plural': 'Dates'},
        ),
        migrations.AlterModelOptions(
            name='news',
            options={'verbose_name': 'News', 'verbose_name_plural': 'News'},
        ),
    ]
